name: Setup CI

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: 20

runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Install dependencies
      if: inputs.node-version >= 14
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Install dependencies with --ignore-engines
      if: inputs.node-version < 14
      shell: bash
      run: yarn install --frozen-lockfile --ignore-engines
